version: '3.4'

networks:
  callData:
    name: callData

services:

  ipfs0:
    container_name: call_ipfs0
    image: ipfs/kubo:release
    ports:
      - "127.0.0.100:8080:8080"
    volumes:
      - ../../data/ipfs0:/data/ipfs
    networks:
      - callData

  cluster0:
    container_name: call_data_cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET_NAD}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s
    ports:
      - "127.0.0.100:9094:9094"
    volumes:
      - ../../data/cluster0:/data/ipfs-cluster
    networks:
      - callData

  ipfs1:
    container_name: call_ipfs1
    image: ipfs/kubo:release
    volumes:
      - ../../data/ipfs1:/data/ipfs
    networks:
      - callData

  cluster1:
    container_name: call_data_cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET_NAD}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s
    volumes:
      - ../../data/cluster1:/data/ipfs-cluster
    networks:
      - callData
